export type Cuisine = 'italian' | 'japanese' | 'mexican' | 'american' | 'chinese' | 'indian' | 'mediterranean';

export type DishTag = 'spicy' | 'vegetarian' | 'vegan' | 'gluten-free' | 'popular' | 'new';

export interface Dish {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  tags: DishTag[];
  category: string;
  restaurantId: string;
}

export interface Restaurant {
  id: string;
  name: string;
  description: string;
  cuisine: Cuisine;
  heroImage: string;
  rating: number;
  deliveryTime: string;
  deliveryFee: number;
  minOrder: number;
  tags: DishTag[];
}

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Bella Napoli',
    description: 'Autentica cucina napoletana con ingredienti freschi',
    cuisine: 'italian',
    heroImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    rating: 4.8,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minOrder: 15,
    tags: ['vegetarian'],
  },
  {
    id: '2',
    name: 'Sushi Master',
    description: 'Il miglior sushi della città, fresco ogni giorno',
    cuisine: 'japanese',
    heroImage: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
    rating: 4.9,
    deliveryTime: '30-40 min',
    deliveryFee: 3.49,
    minOrder: 20,
    tags: ['gluten-free'],
  },
  {
    id: '3',
    name: 'Taco Fiesta',
    description: 'Tacos autentici e burritos esplosivi',
    cuisine: 'mexican',
    heroImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
    rating: 4.6,
    deliveryTime: '20-30 min',
    deliveryFee: 1.99,
    minOrder: 12,
    tags: ['spicy', 'vegetarian'],
  },
  {
    id: '4',
    name: 'Burger Kingdom',
    description: 'Hamburger gourmet e patatine croccanti',
    cuisine: 'american',
    heroImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    rating: 4.5,
    deliveryTime: '25-35 min',
    deliveryFee: 2.49,
    minOrder: 10,
    tags: ['popular'],
  },
  {
    id: '5',
    name: 'Dragon Wok',
    description: 'Cucina cinese tradizionale e moderna',
    cuisine: 'chinese',
    heroImage: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800&q=80',
    rating: 4.7,
    deliveryTime: '30-40 min',
    deliveryFee: 2.99,
    minOrder: 18,
    tags: ['spicy', 'vegan'],
  },
  {
    id: '6',
    name: 'Tandoori Palace',
    description: 'Spezie indiane e sapori autentici',
    cuisine: 'indian',
    heroImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    rating: 4.8,
    deliveryTime: '35-45 min',
    deliveryFee: 3.49,
    minOrder: 15,
    tags: ['spicy', 'vegetarian', 'vegan'],
  },
  {
    id: '7',
    name: 'Mediterranean Breeze',
    description: 'Piatti freschi dal Mediterraneo',
    cuisine: 'mediterranean',
    heroImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    rating: 4.7,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minOrder: 16,
    tags: ['vegetarian', 'gluten-free'],
  },
  {
    id: '8',
    name: 'Pizza Express',
    description: 'Pizza napoletana cotta nel forno a legna',
    cuisine: 'italian',
    heroImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
    rating: 4.6,
    deliveryTime: '20-30 min',
    deliveryFee: 1.99,
    minOrder: 12,
    tags: ['popular', 'vegetarian'],
  },
];

export const dishes: Dish[] = [
  // Bella Napoli
  {
    id: 'd1',
    restaurantId: '1',
    name: 'Margherita Classica',
    description: 'Pomodoro San Marzano, mozzarella di bufala, basilico fresco',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80',
    tags: ['vegetarian', 'popular'],
    category: 'Pizze',
  },
  {
    id: 'd2',
    restaurantId: '1',
    name: 'Diavola Piccante',
    description: 'Salame piccante, mozzarella, peperoncino fresco',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80',
    tags: ['spicy', 'popular'],
    category: 'Pizze',
  },
  {
    id: 'd3',
    restaurantId: '1',
    name: 'Pasta Carbonara',
    description: 'Guanciale croccante, uova, pecorino romano',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&q=80',
    tags: ['popular'],
    category: 'Pasta',
  },
  {
    id: 'd4',
    restaurantId: '1',
    name: 'Tiramisù',
    description: 'Classico dolce italiano con caffè e mascarpone',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80',
    tags: ['vegetarian'],
    category: 'Dolci',
  },

  // Sushi Master
  {
    id: 'd5',
    restaurantId: '2',
    name: 'Sushi Mix (20 pezzi)',
    description: 'Selezione mista di nigiri e hosomaki',
    price: 24.90,
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&q=80',
    tags: ['popular', 'gluten-free'],
    category: 'Sushi',
  },
  {
    id: 'd6',
    restaurantId: '2',
    name: 'Salmon Dragon Roll',
    description: 'Salmone, avocado, cream cheese, tobiko',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1617196034183-421b4917c92d?w=400&q=80',
    tags: ['popular'],
    category: 'Uramaki',
  },
  {
    id: 'd7',
    restaurantId: '2',
    name: 'Ramen Tonkotsu',
    description: 'Brodo di maiale, noodles, uovo marinato, cipollotti',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80',
    tags: ['popular'],
    category: 'Ramen',
  },
  {
    id: 'd8',
    restaurantId: '2',
    name: 'Edamame',
    description: 'Fagioli di soia al vapore con sale marino',
    price: 4.50,
    image: 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=400&q=80',
    tags: ['vegan', 'gluten-free'],
    category: 'Antipasti',
  },

  // Taco Fiesta
  {
    id: 'd9',
    restaurantId: '3',
    name: 'Tacos al Pastor (3pz)',
    description: 'Maiale marinato, ananas, cipolla, coriandolo',
    price: 10.90,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80',
    tags: ['spicy', 'popular'],
    category: 'Tacos',
  },
  {
    id: 'd10',
    restaurantId: '3',
    name: 'Burrito Supreme',
    description: 'Pollo, riso, fagioli neri, pico de gallo, guacamole',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&q=80',
    tags: ['popular'],
    category: 'Burritos',
  },
  {
    id: 'd11',
    restaurantId: '3',
    name: 'Quesadilla Vegetariana',
    description: 'Formaggio, peperoni, cipolle, funghi',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=400&q=80',
    tags: ['vegetarian'],
    category: 'Quesadillas',
  },
  {
    id: 'd12',
    restaurantId: '3',
    name: 'Nachos Supreme',
    description: 'Tortilla chips, formaggio fuso, jalapeños, salsa',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&q=80',
    tags: ['spicy', 'vegetarian'],
    category: 'Antipasti',
  },

  // Burger Kingdom
  {
    id: 'd13',
    restaurantId: '4',
    name: 'Classic Cheeseburger',
    description: 'Manzo 200g, cheddar, lattuga, pomodoro, salse speciali',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80',
    tags: ['popular'],
    category: 'Burgers',
  },
  {
    id: 'd14',
    restaurantId: '4',
    name: 'BBQ Bacon Burger',
    description: 'Manzo, bacon croccante, cipolle caramellate, salsa BBQ',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&q=80',
    tags: ['popular'],
    category: 'Burgers',
  },
  {
    id: 'd15',
    restaurantId: '4',
    name: 'Patatine Deluxe',
    description: 'Patatine fritte con cheddar fuso e bacon',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80',
    tags: ['popular'],
    category: 'Contorni',
  },
  {
    id: 'd16',
    restaurantId: '4',
    name: 'Chicken Wings (8pz)',
    description: 'Alette di pollo fritte con salsa BBQ o Buffalo',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&q=80',
    tags: ['spicy'],
    category: 'Antipasti',
  },

  // Dragon Wok
  {
    id: 'd17',
    restaurantId: '5',
    name: 'Pollo Kung Pao',
    description: 'Pollo, arachidi, peperoncini secchi, salsa agrodolce',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&q=80',
    tags: ['spicy', 'popular'],
    category: 'Secondi',
  },
  {
    id: 'd18',
    restaurantId: '5',
    name: 'Noodles Saltati',
    description: 'Noodles con verdure miste e salsa di soia',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80',
    tags: ['vegan'],
    category: 'Noodles',
  },
  {
    id: 'd19',
    restaurantId: '5',
    name: 'Ravioli al Vapore (8pz)',
    description: 'Ravioli ripieni di gamberi e maiale',
    price: 8.90,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&q=80',
    tags: ['popular'],
    category: 'Antipasti',
  },
  {
    id: 'd20',
    restaurantId: '5',
    name: 'Anatra Laccata',
    description: 'Anatra croccante con pancakes e salsa hoisin',
    price: 16.90,
    image: 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=400&q=80',
    tags: ['popular'],
    category: 'Secondi',
  },

  // Tandoori Palace
  {
    id: 'd21',
    restaurantId: '6',
    name: 'Chicken Tikka Masala',
    description: 'Pollo tandoori in salsa cremosa di pomodoro',
    price: 13.90,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    tags: ['spicy', 'popular'],
    category: 'Curry',
  },
  {
    id: 'd22',
    restaurantId: '6',
    name: 'Palak Paneer',
    description: 'Formaggio indiano in salsa di spinaci e spezie',
    price: 11.50,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
    tags: ['vegetarian', 'spicy'],
    category: 'Curry',
  },
  {
    id: 'd23',
    restaurantId: '6',
    name: 'Naan al Burro',
    description: 'Pane indiano morbido spennellato con burro',
    price: 3.50,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80',
    tags: ['vegetarian'],
    category: 'Contorni',
  },
  {
    id: 'd24',
    restaurantId: '6',
    name: 'Samosa (4pz)',
    description: 'Fagottini fritti ripieni di patate e piselli speziati',
    price: 6.90,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
    tags: ['vegetarian', 'vegan'],
    category: 'Antipasti',
  },

  // Mediterranean Breeze
  {
    id: 'd25',
    restaurantId: '7',
    name: 'Piatto Misto Greco',
    description: 'Gyros, tzatziki, insalata greca, pita',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80',
    tags: ['gluten-free', 'popular'],
    category: 'Piatti Unici',
  },
  {
    id: 'd26',
    restaurantId: '7',
    name: 'Falafel Wrap',
    description: 'Polpette di ceci, hummus, verdure fresche, tahini',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1625937329935-d7363ee3a87a?w=400&q=80',
    tags: ['vegan', 'vegetarian'],
    category: 'Wrap',
  },
  {
    id: 'd27',
    restaurantId: '7',
    name: 'Insalata Greca',
    description: 'Pomodori, cetrioli, olive, feta, cipolla rossa',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
    tags: ['vegetarian', 'gluten-free'],
    category: 'Insalate',
  },
  {
    id: 'd28',
    restaurantId: '7',
    name: 'Hummus con Pita',
    description: 'Crema di ceci con pane pita caldo',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400&q=80',
    tags: ['vegan', 'vegetarian'],
    category: 'Antipasti',
  },

  // Pizza Express
  {
    id: 'd29',
    restaurantId: '8',
    name: 'Quattro Formaggi',
    description: 'Mozzarella, gorgonzola, fontina, parmigiano',
    price: 12.90,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80',
    tags: ['vegetarian', 'popular'],
    category: 'Pizze',
  },
  {
    id: 'd30',
    restaurantId: '8',
    name: 'Prosciutto e Funghi',
    description: 'Prosciutto cotto, funghi champignon, mozzarella',
    price: 11.50,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    tags: ['popular'],
    category: 'Pizze',
  },
  {
    id: 'd31',
    restaurantId: '8',
    name: 'Capricciosa',
    description: 'Prosciutto, funghi, carciofi, olive, mozzarella',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400&q=80',
    tags: [],
    category: 'Pizze',
  },
  {
    id: 'd32',
    restaurantId: '8',
    name: 'Panna Cotta',
    description: 'Dolce cremoso con coulis di frutti di bosco',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
    tags: ['vegetarian'],
    category: 'Dolci',
  },
];

export const cuisineLabels: Record<Cuisine, string> = {
  italian: 'Italiana',
  japanese: 'Giapponese',
  mexican: 'Messicana',
  american: 'Americana',
  chinese: 'Cinese',
  indian: 'Indiana',
  mediterranean: 'Mediterranea',
};

export const tagLabels: Record<DishTag, string> = {
  spicy: 'Piccante',
  vegetarian: 'Vegetariano',
  vegan: 'Vegano',
  'gluten-free': 'Senza Glutine',
  popular: 'Popolare',
  new: 'Novità',
};
