import { Event, Organizer, Speaker, Category } from "./types";

// Helper to create dates relative to today
const daysFromNow = (days: number, hours = 9) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hours, 0, 0, 0);
  return date;
};

// Organizers
export const organizers: Organizer[] = [
  {
    id: "org_001",
    name: "TechConf Global",
    logo: "/images/categories/tech.jpg",
    bio: "Premier technology conference organizer bringing together innovators worldwide since 2015.",
    website: "https://techconfglobal.com",
    eventsCount: 24,
  },
  {
    id: "org_002",
    name: "SoundWave Productions",
    logo: "/images/categories/music.jpg",
    bio: "Creating unforgettable music experiences across the globe.",
    website: "https://soundwaveproductions.com",
    eventsCount: 156,
  },
  {
    id: "org_003",
    name: "Culinary Arts Collective",
    logo: "/images/categories/food.jpg",
    bio: "Celebrating food culture through immersive culinary experiences.",
    website: "https://culinaryartscollective.com",
    eventsCount: 89,
  },
  {
    id: "org_004",
    name: "Urban Fitness Club",
    logo: "/images/categories/health.jpg",
    bio: "Empowering communities through fitness and wellness programs.",
    eventsCount: 234,
  },
  {
    id: "org_005",
    name: "Creative Space Studios",
    logo: "/images/categories/arts.jpg",
    bio: "Supporting artists and bringing creativity to communities since 2010.",
    website: "https://creativespacestudios.com",
    eventsCount: 67,
  },
  {
    id: "org_006",
    name: "Business Network Alliance",
    logo: "/images/categories/networking.jpg",
    bio: "Connecting professionals and fostering business growth.",
    website: "https://businessnetworkalliance.com",
    eventsCount: 145,
  },
  {
    id: "org_007",
    name: "LearnHub Academy",
    logo: "/images/categories/education.jpg",
    bio: "Making quality education accessible through workshops and courses.",
    eventsCount: 312,
  },
  {
    id: "org_008",
    name: "Sports United",
    logo: "/images/categories/sports.jpg",
    bio: "Bringing fans together for the biggest sporting events.",
    eventsCount: 78,
  },
];

// Speakers
export const speakers: Speaker[] = [
  {
    id: "spk_001",
    name: "Sarah Chen",
    title: "Chief Technology Officer",
    company: "Innovate Labs",
    bio: "15+ years building scalable systems at top tech companies. Former engineering lead at Google.",
    photo: "/images/speakers/speaker-2.jpg",
    social: { twitter: "@sarahchen_tech", linkedin: "sarahchen" },
  },
  {
    id: "spk_002",
    name: "Marcus Johnson",
    title: "AI Research Director",
    company: "DeepMind",
    bio: "Leading researcher in machine learning and neural networks with 50+ published papers.",
    photo: "/images/speakers/speaker-1.jpg",
    social: { twitter: "@marcusj_ai", linkedin: "marcusjohnson" },
  },
  {
    id: "spk_003",
    name: "Elena Rodriguez",
    title: "Product Design Lead",
    company: "Figma",
    bio: "Award-winning designer focused on creating intuitive user experiences.",
    photo: "/images/speakers/speaker-4.jpg",
    social: { twitter: "@elenarodriguez", linkedin: "elenarodriguez" },
  },
  {
    id: "spk_004",
    name: "David Park",
    title: "Startup Founder & CEO",
    company: "Velocity Ventures",
    bio: "Serial entrepreneur with 3 successful exits. Angel investor and mentor.",
    photo: "/images/speakers/speaker-3.jpg",
    social: { twitter: "@davidpark_vc", linkedin: "davidpark" },
  },
  {
    id: "spk_005",
    name: "Amara Williams",
    title: "Head of Engineering",
    company: "Stripe",
    bio: "Building payment infrastructure that powers millions of businesses globally.",
    photo: "/images/speakers/speaker-6.jpg",
    social: { linkedin: "amarawilliams" },
  },
  {
    id: "spk_006",
    name: "James Mitchell",
    title: "Executive Chef",
    company: "The Modern Kitchen",
    bio: "Michelin-starred chef with 20 years of culinary excellence.",
    photo: "/images/speakers/speaker-5.jpg",
    social: { twitter: "@chefjames" },
  },
];

// Events
export const events: Event[] = [
  // TECH EVENTS
  {
    id: "evt_001",
    title: "React Summit 2025",
    slug: "react-summit-2025",
    description: "Join 2,000+ developers for the biggest React conference of the year. Learn from industry experts, network with peers, and discover the latest in the React ecosystem. Three days of talks, workshops, and networking opportunities.",
    category: "tech",
    organizer: organizers[0],
    date: {
      start: daysFromNow(15, 9),
      end: daysFromNow(17, 18),
    },
    location: {
      type: "hybrid",
      venue: {
        name: "Moscone Center",
        address: "747 Howard St",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.7844, lng: -122.4008 },
      },
      onlineUrl: "https://stream.reactsummit.com",
    },
    images: {
      hero: "/images/events/tech-conference-1.jpg",
      thumbnail: "/images/events/tech-conference-1.jpg",
    },
    tickets: [
      {
        id: "tkt_001a",
        name: "Online Pass",
        price: 99,
        currency: "USD",
        description: "Full access to live stream",
        features: ["Live stream access", "Q&A participation", "Recording access for 30 days"],
        quantity: { total: 1000, available: 342 },
      },
      {
        id: "tkt_001b",
        name: "In-Person Pass",
        price: 499,
        currency: "USD",
        description: "Full conference access",
        features: ["All talks & workshops", "Networking events", "Lunch included", "Swag bag"],
        quantity: { total: 500, available: 87 },
      },
      {
        id: "tkt_001c",
        name: "VIP Pass",
        price: 899,
        currency: "USD",
        description: "Premium experience",
        features: ["All In-Person benefits", "Speaker dinner", "Priority seating", "1-on-1 mentoring session"],
        quantity: { total: 50, available: 12 },
      },
    ],
    schedule: [
      { id: "sch_001", time: "09:00 AM", title: "Registration & Coffee", description: "Check in and grab your badge", location: "Main Lobby" },
      { id: "sch_002", time: "10:00 AM", title: "Keynote: The Future of React", description: "Opening keynote on React 19 and beyond", speaker: "Sarah Chen", location: "Main Stage" },
      { id: "sch_003", time: "11:30 AM", title: "Building Scalable Apps", description: "Architecture patterns for large React applications", speaker: "Marcus Johnson", location: "Room A" },
      { id: "sch_004", time: "02:00 PM", title: "Design Systems Workshop", description: "Hands-on workshop building component libraries", speaker: "Elena Rodriguez", location: "Workshop Room" },
    ],
    speakers: [speakers[0], speakers[1], speakers[2]],
    tags: ["react", "javascript", "frontend", "web development"],
    stats: { attendees: 1845, views: 12453, saves: 892 },
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "evt_002",
    title: "AI & Machine Learning Conference",
    slug: "ai-ml-conference-2025",
    description: "Explore the cutting edge of artificial intelligence and machine learning. From practical applications to research breakthroughs, discover how AI is transforming industries.",
    category: "tech",
    organizer: organizers[0],
    date: {
      start: daysFromNow(22, 9),
      end: daysFromNow(23, 17),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Convention Center",
        address: "1 Convention Way",
        city: "Austin",
        state: "TX",
        country: "USA",
        coordinates: { lat: 30.2672, lng: -97.7431 },
      },
    },
    images: {
      hero: "/images/events/tech-conference-2.jpg",
      thumbnail: "/images/events/tech-conference-2.jpg",
    },
    tickets: [
      {
        id: "tkt_002a",
        name: "General Admission",
        price: 349,
        currency: "USD",
        description: "Full conference access",
        features: ["All sessions", "Networking lunch", "Conference materials"],
        quantity: { total: 800, available: 234 },
      },
      {
        id: "tkt_002b",
        name: "Workshop Bundle",
        price: 549,
        currency: "USD",
        description: "Conference + hands-on workshops",
        features: ["All General benefits", "2 hands-on workshops", "Certificate of completion"],
        quantity: { total: 200, available: 45 },
      },
    ],
    speakers: [speakers[1], speakers[4]],
    tags: ["AI", "machine learning", "deep learning", "data science"],
    stats: { attendees: 756, views: 8234, saves: 567 },
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "evt_003",
    title: "Startup Founders Meetup",
    slug: "startup-founders-meetup",
    description: "Monthly gathering of startup founders, entrepreneurs, and investors. Share experiences, get feedback, and build meaningful connections in the startup ecosystem.",
    category: "tech",
    organizer: organizers[5],
    date: {
      start: daysFromNow(3, 18),
      end: daysFromNow(3, 21),
    },
    location: {
      type: "in-person",
      venue: {
        name: "WeWork Innovation Hub",
        address: "123 Startup Lane",
        city: "New York",
        state: "NY",
        country: "USA",
        coordinates: { lat: 40.7128, lng: -74.006 },
      },
    },
    images: {
      hero: "/images/events/tech-meetup-1.jpg",
      thumbnail: "/images/events/tech-meetup-1.jpg",
    },
    tickets: [
      {
        id: "tkt_003a",
        name: "Free Entry",
        price: 0,
        currency: "USD",
        description: "RSVP for free entry",
        features: ["Networking session", "Drinks & snacks", "Pitch practice"],
        quantity: { total: 100, available: 23 },
      },
    ],
    tags: ["startups", "networking", "entrepreneurs", "founders"],
    stats: { attendees: 77, views: 1234, saves: 89 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_004",
    title: "DevOps & Cloud Summit",
    slug: "devops-cloud-summit",
    description: "Master the tools and practices that power modern software delivery. Learn Kubernetes, CI/CD pipelines, infrastructure as code, and cloud-native architectures.",
    category: "tech",
    organizer: organizers[0],
    date: {
      start: daysFromNow(30, 9),
      end: daysFromNow(31, 17),
    },
    location: {
      type: "online",
      onlineUrl: "https://devops-summit.live",
    },
    images: {
      hero: "/images/events/tech-meetup-2.jpg",
      thumbnail: "/images/events/tech-meetup-2.jpg",
    },
    tickets: [
      {
        id: "tkt_004a",
        name: "Virtual Pass",
        price: 149,
        currency: "USD",
        description: "Full online access",
        features: ["Live sessions", "Workshops", "Recordings", "Slack community access"],
        quantity: { total: 2000, available: 1456 },
      },
    ],
    tags: ["devops", "kubernetes", "cloud", "AWS", "docker"],
    stats: { attendees: 544, views: 5678, saves: 345 },
    isFeatured: false,
    isTrending: false,
  },

  // MUSIC EVENTS
  {
    id: "evt_005",
    title: "Summer Music Festival 2025",
    slug: "summer-music-festival-2025",
    description: "Three days of incredible live music featuring top artists across multiple stages. Experience everything from indie rock to electronic music in a beautiful outdoor setting.",
    category: "music",
    organizer: organizers[1],
    date: {
      start: daysFromNow(45, 14),
      end: daysFromNow(47, 23),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Golden Gate Park",
        address: "501 Stanyan St",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.7694, lng: -122.4862 },
      },
    },
    images: {
      hero: "/images/events/music-festival-1.jpg",
      thumbnail: "/images/events/music-festival-1.jpg",
    },
    tickets: [
      {
        id: "tkt_005a",
        name: "Single Day Pass",
        price: 125,
        currency: "USD",
        description: "Access to one day",
        features: ["All stages", "Food court access"],
        quantity: { total: 5000, available: 2340 },
      },
      {
        id: "tkt_005b",
        name: "3-Day Pass",
        price: 299,
        currency: "USD",
        description: "Full festival access",
        features: ["All 3 days", "All stages", "Express entry"],
        quantity: { total: 3000, available: 890 },
      },
      {
        id: "tkt_005c",
        name: "VIP Experience",
        price: 599,
        currency: "USD",
        description: "Premium festival experience",
        features: ["All 3-Day benefits", "VIP viewing areas", "Artist meet & greet", "Premium bar access"],
        quantity: { total: 500, available: 67 },
      },
    ],
    tags: ["music", "festival", "outdoor", "live music", "summer"],
    stats: { attendees: 8750, views: 45678, saves: 3456 },
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "evt_006",
    title: "Jazz Night at Blue Note",
    slug: "jazz-night-blue-note",
    description: "An intimate evening of world-class jazz performances. Featuring acclaimed artists in the legendary Blue Note atmosphere.",
    category: "music",
    organizer: organizers[1],
    date: {
      start: daysFromNow(5, 20),
      end: daysFromNow(5, 23),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Blue Note Jazz Club",
        address: "131 W 3rd St",
        city: "New York",
        state: "NY",
        country: "USA",
        coordinates: { lat: 40.7308, lng: -74.0007 },
      },
    },
    images: {
      hero: "/images/events/concert-3.jpg",
      thumbnail: "/images/events/concert-3.jpg",
    },
    tickets: [
      {
        id: "tkt_006a",
        name: "General Seating",
        price: 45,
        currency: "USD",
        description: "Table seating",
        features: ["Reserved table", "Full bar menu available"],
        quantity: { total: 120, available: 34 },
      },
      {
        id: "tkt_006b",
        name: "Premium Front Row",
        price: 85,
        currency: "USD",
        description: "Best seats in the house",
        features: ["Front row table", "Complimentary drink", "Meet the artists"],
        quantity: { total: 20, available: 4 },
      },
    ],
    tags: ["jazz", "live music", "nightlife", "intimate"],
    stats: { attendees: 86, views: 2345, saves: 178 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_007",
    title: "Electronic Music Warehouse Party",
    slug: "electronic-warehouse-party",
    description: "Underground electronic music experience in an iconic warehouse space. World-renowned DJs spinning house, techno, and everything in between.",
    category: "music",
    organizer: organizers[1],
    date: {
      start: daysFromNow(8, 22),
      end: daysFromNow(9, 4),
    },
    location: {
      type: "in-person",
      venue: {
        name: "The Warehouse",
        address: "789 Industrial Blvd",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        coordinates: { lat: 34.0407, lng: -118.2468 },
      },
    },
    images: {
      hero: "/images/events/concert-1.jpg",
      thumbnail: "/images/events/concert-1.jpg",
    },
    tickets: [
      {
        id: "tkt_007a",
        name: "Early Bird",
        price: 35,
        currency: "USD",
        description: "Limited early bird tickets",
        features: ["General admission", "Entry before 11pm"],
        quantity: { total: 200, available: 0 },
      },
      {
        id: "tkt_007b",
        name: "General Admission",
        price: 55,
        currency: "USD",
        description: "Standard entry",
        features: ["General admission"],
        quantity: { total: 800, available: 234 },
      },
    ],
    tags: ["electronic", "house", "techno", "nightlife", "DJ"],
    stats: { attendees: 766, views: 6789, saves: 456 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_008",
    title: "Symphony Orchestra: Beethoven Night",
    slug: "symphony-beethoven-night",
    description: "Experience the timeless masterpieces of Ludwig van Beethoven performed by the City Symphony Orchestra. An evening of classical excellence.",
    category: "music",
    organizer: organizers[1],
    date: {
      start: daysFromNow(12, 19),
      end: daysFromNow(12, 22),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Davies Symphony Hall",
        address: "201 Van Ness Ave",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.7774, lng: -122.4199 },
      },
    },
    images: {
      hero: "/images/events/concert-2.jpg",
      thumbnail: "/images/events/concert-2.jpg",
    },
    tickets: [
      {
        id: "tkt_008a",
        name: "Balcony",
        price: 65,
        currency: "USD",
        description: "Balcony seating",
        features: ["Upper balcony seat", "Program included"],
        quantity: { total: 400, available: 156 },
      },
      {
        id: "tkt_008b",
        name: "Orchestra",
        price: 125,
        currency: "USD",
        description: "Main floor seating",
        features: ["Orchestra level seat", "Program included", "Intermission reception"],
        quantity: { total: 300, available: 89 },
      },
    ],
    tags: ["classical", "symphony", "orchestra", "Beethoven"],
    stats: { attendees: 544, views: 3456, saves: 234 },
    isFeatured: false,
    isTrending: false,
  },

  // FOOD EVENTS
  {
    id: "evt_009",
    title: "Street Food Festival",
    slug: "street-food-festival",
    description: "Discover incredible street food from around the world. Over 50 food vendors, live cooking demonstrations, and a celebration of culinary diversity.",
    category: "food",
    organizer: organizers[2],
    date: {
      start: daysFromNow(10, 11),
      end: daysFromNow(11, 20),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Waterfront Park",
        address: "1 Harbor Dr",
        city: "San Diego",
        state: "CA",
        country: "USA",
        coordinates: { lat: 32.7157, lng: -117.1611 },
      },
    },
    images: {
      hero: "/images/events/food-festival-1.jpg",
      thumbnail: "/images/events/food-festival-1.jpg",
    },
    tickets: [
      {
        id: "tkt_009a",
        name: "General Entry",
        price: 15,
        currency: "USD",
        description: "Festival access",
        features: ["Festival entry", "Access to all vendors"],
        quantity: { total: 2000, available: 876 },
      },
      {
        id: "tkt_009b",
        name: "Tasting Pass",
        price: 45,
        currency: "USD",
        description: "Entry + tasting credits",
        features: ["Festival entry", "$30 in tasting tokens", "Priority entry"],
        quantity: { total: 500, available: 123 },
      },
    ],
    tags: ["food", "street food", "festival", "culinary"],
    stats: { attendees: 1124, views: 8765, saves: 567 },
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "evt_010",
    title: "Italian Cooking Masterclass",
    slug: "italian-cooking-masterclass",
    description: "Learn authentic Italian cooking techniques from a Michelin-starred chef. Make fresh pasta, traditional sauces, and classic desserts.",
    category: "food",
    organizer: organizers[2],
    date: {
      start: daysFromNow(7, 14),
      end: daysFromNow(7, 18),
    },
    location: {
      type: "in-person",
      venue: {
        name: "The Culinary Institute",
        address: "456 Kitchen St",
        city: "Chicago",
        state: "IL",
        country: "USA",
        coordinates: { lat: 41.8781, lng: -87.6298 },
      },
    },
    images: {
      hero: "/images/events/food-cooking-1.jpg",
      thumbnail: "/images/events/food-cooking-1.jpg",
    },
    tickets: [
      {
        id: "tkt_010a",
        name: "Cooking Class",
        price: 150,
        currency: "USD",
        description: "Hands-on cooking experience",
        features: ["4-hour class", "All ingredients provided", "Recipe booklet", "Meal at end"],
        quantity: { total: 20, available: 6 },
      },
    ],
    speakers: [speakers[5]],
    tags: ["cooking", "Italian", "masterclass", "culinary"],
    stats: { attendees: 14, views: 1234, saves: 89 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_011",
    title: "Wine Tasting Evening",
    slug: "wine-tasting-evening",
    description: "Journey through renowned wine regions with our expert sommelier. Sample 12 exceptional wines paired with artisanal cheeses.",
    category: "food",
    organizer: organizers[2],
    date: {
      start: daysFromNow(4, 18),
      end: daysFromNow(4, 21),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Vino Gallery",
        address: "789 Wine Lane",
        city: "Napa",
        state: "CA",
        country: "USA",
        coordinates: { lat: 38.2975, lng: -122.2869 },
      },
    },
    images: {
      hero: "/images/events/food-event-1.jpg",
      thumbnail: "/images/events/food-event-1.jpg",
    },
    tickets: [
      {
        id: "tkt_011a",
        name: "Tasting Experience",
        price: 85,
        currency: "USD",
        description: "Full tasting experience",
        features: ["12 wine samples", "Cheese pairings", "Sommelier guided", "Wine discount voucher"],
        quantity: { total: 40, available: 12 },
      },
    ],
    tags: ["wine", "tasting", "sommelier", "cheese"],
    stats: { attendees: 28, views: 890, saves: 67 },
    isFeatured: false,
    isTrending: true,
  },

  // SPORTS EVENTS
  {
    id: "evt_012",
    title: "City Marathon 2025",
    slug: "city-marathon-2025",
    description: "Run through the most scenic routes of the city in this annual marathon event. Categories for all levels from 5K to full marathon.",
    category: "sports",
    organizer: organizers[7],
    date: {
      start: daysFromNow(35, 6),
      end: daysFromNow(35, 14),
    },
    location: {
      type: "in-person",
      venue: {
        name: "City Center Start Line",
        address: "1 Main Plaza",
        city: "Boston",
        state: "MA",
        country: "USA",
        coordinates: { lat: 42.3601, lng: -71.0589 },
      },
    },
    images: {
      hero: "/images/events/sports-1.jpg",
      thumbnail: "/images/events/sports-1.jpg",
    },
    tickets: [
      {
        id: "tkt_012a",
        name: "5K Run",
        price: 45,
        currency: "USD",
        description: "5K category",
        features: ["5K entry", "Finisher medal", "T-shirt", "Refreshments"],
        quantity: { total: 2000, available: 890 },
      },
      {
        id: "tkt_012b",
        name: "Half Marathon",
        price: 85,
        currency: "USD",
        description: "Half marathon category",
        features: ["Half marathon entry", "Finisher medal", "Premium T-shirt", "Post-race meal"],
        quantity: { total: 1500, available: 456 },
      },
      {
        id: "tkt_012c",
        name: "Full Marathon",
        price: 125,
        currency: "USD",
        description: "Full marathon category",
        features: ["Full marathon entry", "Premium finisher medal", "Technical shirt", "Post-race party"],
        quantity: { total: 1000, available: 234 },
      },
    ],
    tags: ["marathon", "running", "fitness", "outdoor"],
    stats: { attendees: 2420, views: 15678, saves: 1234 },
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "evt_013",
    title: "Basketball Championship Finals",
    slug: "basketball-championship-finals",
    description: "Witness the ultimate showdown as the top two teams battle for the championship title. An electrifying atmosphere guaranteed!",
    category: "sports",
    organizer: organizers[7],
    date: {
      start: daysFromNow(20, 19),
      end: daysFromNow(20, 22),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Madison Square Garden",
        address: "4 Pennsylvania Plaza",
        city: "New York",
        state: "NY",
        country: "USA",
        coordinates: { lat: 40.7505, lng: -73.9934 },
      },
    },
    images: {
      hero: "/images/events/sports-stadium-1.jpg",
      thumbnail: "/images/events/sports-stadium-1.jpg",
    },
    tickets: [
      {
        id: "tkt_013a",
        name: "Upper Level",
        price: 89,
        currency: "USD",
        description: "Upper level seating",
        features: ["Upper level seat", "Game program"],
        quantity: { total: 5000, available: 1234 },
      },
      {
        id: "tkt_013b",
        name: "Lower Level",
        price: 199,
        currency: "USD",
        description: "Lower level seating",
        features: ["Lower level seat", "Game program", "Concession voucher"],
        quantity: { total: 3000, available: 567 },
      },
      {
        id: "tkt_013c",
        name: "Courtside",
        price: 599,
        currency: "USD",
        description: "Courtside experience",
        features: ["Courtside seat", "VIP lounge access", "Meet players opportunity"],
        quantity: { total: 100, available: 8 },
      },
    ],
    tags: ["basketball", "championship", "sports", "live"],
    stats: { attendees: 7766, views: 34567, saves: 2345 },
    isFeatured: true,
    isTrending: true,
  },

  // ARTS EVENTS
  {
    id: "evt_014",
    title: "Contemporary Art Exhibition",
    slug: "contemporary-art-exhibition",
    description: "Explore groundbreaking works from emerging and established contemporary artists. A thought-provoking journey through modern artistic expression.",
    category: "arts",
    organizer: organizers[4],
    date: {
      start: daysFromNow(2, 10),
      end: daysFromNow(30, 18),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Modern Art Museum",
        address: "151 3rd St",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.7857, lng: -122.4011 },
      },
    },
    images: {
      hero: "/images/events/art-exhibition-1.jpg",
      thumbnail: "/images/events/art-exhibition-1.jpg",
    },
    tickets: [
      {
        id: "tkt_014a",
        name: "General Admission",
        price: 25,
        currency: "USD",
        description: "Museum entry",
        features: ["Exhibition access", "Audio guide"],
        quantity: { total: 500, available: 345 },
      },
      {
        id: "tkt_014b",
        name: "Guided Tour",
        price: 45,
        currency: "USD",
        description: "Expert-led tour",
        features: ["Exhibition access", "90-min guided tour", "Exclusive insights"],
        quantity: { total: 30, available: 12 },
      },
    ],
    tags: ["art", "contemporary", "exhibition", "museum"],
    stats: { attendees: 155, views: 4567, saves: 234 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_015",
    title: "Watercolor Painting Workshop",
    slug: "watercolor-painting-workshop",
    description: "Discover the beautiful world of watercolor painting. Learn techniques from basic washes to advanced layering in this hands-on workshop.",
    category: "arts",
    organizer: organizers[4],
    date: {
      start: daysFromNow(6, 13),
      end: daysFromNow(6, 17),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Creative Space Studios",
        address: "234 Art District",
        city: "Portland",
        state: "OR",
        country: "USA",
        coordinates: { lat: 45.5152, lng: -122.6784 },
      },
    },
    images: {
      hero: "/images/events/art-workshop-1.jpg",
      thumbnail: "/images/events/art-workshop-1.jpg",
    },
    tickets: [
      {
        id: "tkt_015a",
        name: "Workshop Entry",
        price: 75,
        currency: "USD",
        description: "All materials included",
        features: ["4-hour workshop", "All supplies provided", "Take home your artwork", "Refreshments"],
        quantity: { total: 15, available: 5 },
      },
    ],
    tags: ["art", "watercolor", "painting", "workshop", "creative"],
    stats: { attendees: 10, views: 678, saves: 45 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_016",
    title: "Photography Gallery Night",
    slug: "photography-gallery-night",
    description: "An evening celebrating photography as fine art. Meet the photographers, enjoy wine and appetizers, and explore stunning visual narratives.",
    category: "arts",
    organizer: organizers[4],
    date: {
      start: daysFromNow(9, 18),
      end: daysFromNow(9, 22),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Aperture Gallery",
        address: "547 W 27th St",
        city: "New York",
        state: "NY",
        country: "USA",
        coordinates: { lat: 40.7516, lng: -74.0045 },
      },
    },
    images: {
      hero: "/images/events/art-gallery-1.jpg",
      thumbnail: "/images/events/art-gallery-1.jpg",
    },
    tickets: [
      {
        id: "tkt_016a",
        name: "Gallery Entry",
        price: 0,
        currency: "USD",
        description: "Free entry with RSVP",
        features: ["Gallery access", "Wine & appetizers", "Meet the artists"],
        quantity: { total: 100, available: 34 },
      },
    ],
    tags: ["photography", "gallery", "art", "free", "networking"],
    stats: { attendees: 66, views: 1234, saves: 89 },
    isFeatured: false,
    isTrending: true,
  },

  // NETWORKING EVENTS
  {
    id: "evt_017",
    title: "Tech Professionals Mixer",
    slug: "tech-professionals-mixer",
    description: "Connect with fellow tech professionals in a relaxed, social setting. Build your network, share ideas, and explore collaboration opportunities.",
    category: "networking",
    organizer: organizers[5],
    date: {
      start: daysFromNow(1, 18),
      end: daysFromNow(1, 21),
    },
    location: {
      type: "in-person",
      venue: {
        name: "The Rooftop Lounge",
        address: "100 Tech Center Dr",
        city: "Seattle",
        state: "WA",
        country: "USA",
        coordinates: { lat: 47.6062, lng: -122.3321 },
      },
    },
    images: {
      hero: "/images/events/networking-1.jpg",
      thumbnail: "/images/events/networking-1.jpg",
    },
    tickets: [
      {
        id: "tkt_017a",
        name: "Networking Pass",
        price: 25,
        currency: "USD",
        description: "Entry with drink tickets",
        features: ["Event entry", "2 drink tickets", "Appetizers", "LinkedIn networking session"],
        quantity: { total: 150, available: 67 },
      },
    ],
    tags: ["networking", "tech", "professionals", "social"],
    stats: { attendees: 83, views: 2345, saves: 123 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_018",
    title: "Women in Leadership Summit",
    slug: "women-leadership-summit",
    description: "Empowering women leaders through inspiring talks, workshops, and networking. Connect with successful women across industries.",
    category: "networking",
    organizer: organizers[5],
    date: {
      start: daysFromNow(25, 8),
      end: daysFromNow(25, 18),
    },
    location: {
      type: "hybrid",
      venue: {
        name: "Grand Hyatt Hotel",
        address: "345 Stockton St",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.7879, lng: -122.4074 },
      },
      onlineUrl: "https://womenleadership.live",
    },
    images: {
      hero: "/images/events/networking-2.jpg",
      thumbnail: "/images/events/networking-2.jpg",
    },
    tickets: [
      {
        id: "tkt_018a",
        name: "Virtual Attendance",
        price: 99,
        currency: "USD",
        description: "Online access",
        features: ["Live stream", "Q&A participation", "Digital resources", "Online networking"],
        quantity: { total: 500, available: 234 },
      },
      {
        id: "tkt_018b",
        name: "In-Person",
        price: 299,
        currency: "USD",
        description: "Full summit access",
        features: ["All sessions", "Networking lunch", "Workshop access", "Swag bag"],
        quantity: { total: 200, available: 45 },
      },
    ],
    speakers: [speakers[0], speakers[2], speakers[4]],
    tags: ["women", "leadership", "networking", "empowerment", "professional development"],
    stats: { attendees: 421, views: 8765, saves: 567 },
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "evt_019",
    title: "Investor Pitch Night",
    slug: "investor-pitch-night",
    description: "Startups pitch to angel investors and VCs. A high-energy evening of innovation, entrepreneurship, and investment opportunities.",
    category: "networking",
    organizer: organizers[5],
    date: {
      start: daysFromNow(14, 18),
      end: daysFromNow(14, 21),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Innovation Hub",
        address: "500 Startup Way",
        city: "Palo Alto",
        state: "CA",
        country: "USA",
        coordinates: { lat: 37.4419, lng: -122.143 },
      },
    },
    images: {
      hero: "/images/events/business-1.jpg",
      thumbnail: "/images/events/business-1.jpg",
    },
    tickets: [
      {
        id: "tkt_019a",
        name: "Spectator",
        price: 35,
        currency: "USD",
        description: "Watch the pitches",
        features: ["Event access", "Networking session", "Drinks & snacks"],
        quantity: { total: 100, available: 45 },
      },
      {
        id: "tkt_019b",
        name: "Startup Pitch Slot",
        price: 150,
        currency: "USD",
        description: "5-minute pitch opportunity",
        features: ["Pitch slot", "Investor feedback", "Networking priority", "Follow-up introductions"],
        quantity: { total: 10, available: 2 },
      },
    ],
    speakers: [speakers[3]],
    tags: ["startup", "investment", "pitch", "VC", "entrepreneurs"],
    stats: { attendees: 108, views: 3456, saves: 234 },
    isFeatured: false,
    isTrending: true,
  },

  // EDUCATION EVENTS
  {
    id: "evt_020",
    title: "Data Science Bootcamp",
    slug: "data-science-bootcamp",
    description: "Intensive 2-day bootcamp covering Python, machine learning, and data visualization. Perfect for beginners wanting to enter the field.",
    category: "education",
    organizer: organizers[6],
    date: {
      start: daysFromNow(18, 9),
      end: daysFromNow(19, 17),
    },
    location: {
      type: "hybrid",
      venue: {
        name: "TechSpace Academy",
        address: "200 Learning Lane",
        city: "Denver",
        state: "CO",
        country: "USA",
        coordinates: { lat: 39.7392, lng: -104.9903 },
      },
      onlineUrl: "https://datascience.bootcamp.live",
    },
    images: {
      hero: "/images/events/education-1.jpg",
      thumbnail: "/images/events/education-1.jpg",
    },
    tickets: [
      {
        id: "tkt_020a",
        name: "Online Bootcamp",
        price: 299,
        currency: "USD",
        description: "Virtual attendance",
        features: ["Live sessions", "Hands-on projects", "Certificate", "Community access"],
        quantity: { total: 100, available: 56 },
      },
      {
        id: "tkt_020b",
        name: "In-Person Bootcamp",
        price: 499,
        currency: "USD",
        description: "On-site experience",
        features: ["All online benefits", "In-person instruction", "Networking lunch", "Career guidance session"],
        quantity: { total: 30, available: 8 },
      },
    ],
    tags: ["data science", "python", "bootcamp", "education", "career"],
    stats: { attendees: 66, views: 5678, saves: 345 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_021",
    title: "Public Speaking Masterclass",
    slug: "public-speaking-masterclass",
    description: "Overcome your fear of public speaking and become a confident presenter. Learn techniques used by world-class speakers.",
    category: "education",
    organizer: organizers[6],
    date: {
      start: daysFromNow(11, 9),
      end: daysFromNow(11, 17),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Communication Center",
        address: "321 Speaker St",
        city: "Atlanta",
        state: "GA",
        country: "USA",
        coordinates: { lat: 33.749, lng: -84.388 },
      },
    },
    images: {
      hero: "/images/events/workshop-1.jpg",
      thumbnail: "/images/events/workshop-1.jpg",
    },
    tickets: [
      {
        id: "tkt_021a",
        name: "Workshop Pass",
        price: 199,
        currency: "USD",
        description: "Full-day workshop",
        features: ["8-hour workshop", "Practice sessions", "Video recording of your speech", "Personalized feedback"],
        quantity: { total: 25, available: 9 },
      },
    ],
    tags: ["public speaking", "communication", "workshop", "professional development"],
    stats: { attendees: 16, views: 2345, saves: 167 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_022",
    title: "UX Design Fundamentals",
    slug: "ux-design-fundamentals",
    description: "Learn the foundations of user experience design. From research to prototyping, master the skills needed to create user-centered products.",
    category: "education",
    organizer: organizers[6],
    date: {
      start: daysFromNow(28, 10),
      end: daysFromNow(29, 16),
    },
    location: {
      type: "online",
      onlineUrl: "https://uxdesign.workshop.live",
    },
    images: {
      hero: "/images/events/education-2.jpg",
      thumbnail: "/images/events/education-2.jpg",
    },
    tickets: [
      {
        id: "tkt_022a",
        name: "Course Access",
        price: 249,
        currency: "USD",
        description: "Complete online course",
        features: ["12 hours of content", "Design exercises", "Portfolio project", "Certificate", "Lifetime access"],
        quantity: { total: 200, available: 134 },
      },
    ],
    speakers: [speakers[2]],
    tags: ["UX", "design", "user experience", "product design", "online course"],
    stats: { attendees: 66, views: 4567, saves: 289 },
    isFeatured: false,
    isTrending: true,
  },

  // HEALTH EVENTS
  {
    id: "evt_023",
    title: "Yoga & Wellness Retreat",
    slug: "yoga-wellness-retreat",
    description: "A rejuvenating day of yoga, meditation, and wellness workshops. Reconnect with yourself in a peaceful outdoor setting.",
    category: "health",
    organizer: organizers[3],
    date: {
      start: daysFromNow(16, 7),
      end: daysFromNow(16, 18),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Serenity Gardens",
        address: "1000 Peaceful Way",
        city: "Sedona",
        state: "AZ",
        country: "USA",
        coordinates: { lat: 34.8697, lng: -111.761 },
      },
    },
    images: {
      hero: "/images/events/wellness-1.jpg",
      thumbnail: "/images/events/wellness-1.jpg",
    },
    tickets: [
      {
        id: "tkt_023a",
        name: "Full Day Retreat",
        price: 149,
        currency: "USD",
        description: "Complete wellness experience",
        features: ["Morning yoga", "Meditation sessions", "Healthy lunch", "Wellness workshops", "Sound healing"],
        quantity: { total: 50, available: 18 },
      },
    ],
    tags: ["yoga", "wellness", "meditation", "retreat", "health"],
    stats: { attendees: 32, views: 3456, saves: 234 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_024",
    title: "HIIT Fitness Challenge",
    slug: "hiit-fitness-challenge",
    description: "Push your limits in this high-intensity interval training event. Professional trainers, great music, and an energetic community.",
    category: "health",
    organizer: organizers[3],
    date: {
      start: daysFromNow(5, 8),
      end: daysFromNow(5, 10),
    },
    location: {
      type: "in-person",
      venue: {
        name: "FitZone Gym",
        address: "456 Fitness Ave",
        city: "Miami",
        state: "FL",
        country: "USA",
        coordinates: { lat: 25.7617, lng: -80.1918 },
      },
    },
    images: {
      hero: "/images/events/fitness-1.jpg",
      thumbnail: "/images/events/fitness-1.jpg",
    },
    tickets: [
      {
        id: "tkt_024a",
        name: "Participant",
        price: 35,
        currency: "USD",
        description: "Join the challenge",
        features: ["2-hour HIIT session", "Professional trainers", "Energy drinks", "Finisher T-shirt"],
        quantity: { total: 100, available: 34 },
      },
    ],
    tags: ["fitness", "HIIT", "workout", "gym", "health"],
    stats: { attendees: 66, views: 2345, saves: 123 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_025",
    title: "Mental Health Awareness Workshop",
    slug: "mental-health-workshop",
    description: "Learn practical strategies for managing stress, anxiety, and maintaining mental wellness. Expert-led sessions in a supportive environment.",
    category: "health",
    organizer: organizers[3],
    date: {
      start: daysFromNow(13, 10),
      end: daysFromNow(13, 16),
    },
    location: {
      type: "hybrid",
      venue: {
        name: "Wellness Center",
        address: "789 Health St",
        city: "Portland",
        state: "OR",
        country: "USA",
        coordinates: { lat: 45.5152, lng: -122.6784 },
      },
      onlineUrl: "https://mentalhealth.workshop.live",
    },
    images: {
      hero: "/images/events/health-1.jpg",
      thumbnail: "/images/events/health-1.jpg",
    },
    tickets: [
      {
        id: "tkt_025a",
        name: "Online Access",
        price: 0,
        currency: "USD",
        description: "Free online participation",
        features: ["Live stream", "Q&A session", "Resource materials"],
        quantity: { total: 500, available: 234 },
      },
      {
        id: "tkt_025b",
        name: "In-Person",
        price: 25,
        currency: "USD",
        description: "Attend in person",
        features: ["All online benefits", "Small group discussions", "Networking", "Light refreshments"],
        quantity: { total: 40, available: 12 },
      },
    ],
    tags: ["mental health", "wellness", "stress management", "self-care", "workshop"],
    stats: { attendees: 294, views: 5678, saves: 456 },
    isFeatured: true,
    isTrending: false,
  },

  // Additional events to reach 30+
  {
    id: "evt_026",
    title: "Craft Beer Festival",
    slug: "craft-beer-festival",
    description: "Sample over 100 craft beers from local and regional breweries. Live music, food trucks, and brewing demonstrations.",
    category: "food",
    organizer: organizers[2],
    date: {
      start: daysFromNow(21, 12),
      end: daysFromNow(21, 20),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Brewery District Park",
        address: "100 Brew Lane",
        city: "Portland",
        state: "OR",
        country: "USA",
        coordinates: { lat: 45.5231, lng: -122.6765 },
      },
    },
    images: {
      hero: "/images/events/food-event-1.jpg",
      thumbnail: "/images/events/food-event-1.jpg",
    },
    tickets: [
      {
        id: "tkt_026a",
        name: "Tasting Pass",
        price: 55,
        currency: "USD",
        description: "Unlimited tastings",
        features: ["Unlimited 4oz pours", "Souvenir glass", "Live entertainment"],
        quantity: { total: 1000, available: 456 },
      },
      {
        id: "tkt_026b",
        name: "Designated Driver",
        price: 15,
        currency: "USD",
        description: "Non-alcoholic entry",
        features: ["Event entry", "Free soft drinks", "Food discounts"],
        quantity: { total: 200, available: 89 },
      },
    ],
    tags: ["beer", "craft beer", "festival", "food", "drinks"],
    stats: { attendees: 544, views: 6789, saves: 345 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_027",
    title: "Indie Rock Showcase",
    slug: "indie-rock-showcase",
    description: "Discover the next big thing in indie rock. Five up-and-coming bands performing live in an intimate venue.",
    category: "music",
    organizer: organizers[1],
    date: {
      start: daysFromNow(3, 19),
      end: daysFromNow(3, 23),
    },
    location: {
      type: "in-person",
      venue: {
        name: "The Basement",
        address: "234 Underground St",
        city: "Nashville",
        state: "TN",
        country: "USA",
        coordinates: { lat: 36.1627, lng: -86.7816 },
      },
    },
    images: {
      hero: "/images/events/concert-1.jpg",
      thumbnail: "/images/events/concert-1.jpg",
    },
    tickets: [
      {
        id: "tkt_027a",
        name: "General Admission",
        price: 20,
        currency: "USD",
        description: "Standing room",
        features: ["Entry", "5 bands"],
        quantity: { total: 200, available: 78 },
      },
    ],
    tags: ["indie", "rock", "live music", "bands", "underground"],
    stats: { attendees: 122, views: 2345, saves: 167 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_028",
    title: "Blockchain & Web3 Conference",
    slug: "blockchain-web3-conference",
    description: "Explore the future of decentralized technology. Talks on DeFi, NFTs, DAOs, and the evolving Web3 landscape.",
    category: "tech",
    organizer: organizers[0],
    date: {
      start: daysFromNow(40, 9),
      end: daysFromNow(41, 17),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Crypto Convention Center",
        address: "1 Block Chain Ave",
        city: "Miami",
        state: "FL",
        country: "USA",
        coordinates: { lat: 25.7617, lng: -80.1918 },
      },
    },
    images: {
      hero: "/images/events/tech-conference-2.jpg",
      thumbnail: "/images/events/tech-conference-2.jpg",
    },
    tickets: [
      {
        id: "tkt_028a",
        name: "Conference Pass",
        price: 399,
        currency: "USD",
        description: "Full conference access",
        features: ["All talks", "Networking events", "NFT collectible badge"],
        quantity: { total: 600, available: 234 },
      },
      {
        id: "tkt_028b",
        name: "Builder Pass",
        price: 699,
        currency: "USD",
        description: "Conference + hackathon",
        features: ["All conference benefits", "Hackathon entry", "Mentorship sessions", "Prize pool eligibility"],
        quantity: { total: 150, available: 45 },
      },
    ],
    tags: ["blockchain", "web3", "crypto", "DeFi", "NFT"],
    stats: { attendees: 466, views: 8765, saves: 567 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_029",
    title: "Stand-Up Comedy Night",
    slug: "standup-comedy-night",
    description: "Laugh out loud with some of the funniest comedians in the country. A night of non-stop entertainment.",
    category: "arts",
    organizer: organizers[4],
    date: {
      start: daysFromNow(2, 20),
      end: daysFromNow(2, 23),
    },
    location: {
      type: "in-person",
      venue: {
        name: "The Laugh Factory",
        address: "8001 Sunset Blvd",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        coordinates: { lat: 34.0977, lng: -118.3617 },
      },
    },
    images: {
      hero: "/images/events/art-gallery-1.jpg",
      thumbnail: "/images/events/art-gallery-1.jpg",
    },
    tickets: [
      {
        id: "tkt_029a",
        name: "General Admission",
        price: 25,
        currency: "USD",
        description: "Standard seating",
        features: ["Entry", "2-drink minimum at venue"],
        quantity: { total: 300, available: 123 },
      },
      {
        id: "tkt_029b",
        name: "VIP Table",
        price: 100,
        currency: "USD",
        description: "Front table for 4",
        features: ["Premium table", "Bottle service", "Meet the comedians"],
        quantity: { total: 20, available: 6 },
      },
    ],
    tags: ["comedy", "standup", "entertainment", "nightlife", "fun"],
    stats: { attendees: 177, views: 3456, saves: 234 },
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "evt_030",
    title: "Morning Meditation Sessions",
    slug: "morning-meditation-sessions",
    description: "Start your day with peace and clarity. Weekly guided meditation sessions in a beautiful park setting.",
    category: "health",
    organizer: organizers[3],
    date: {
      start: daysFromNow(0, 7),
      end: daysFromNow(0, 8),
    },
    location: {
      type: "in-person",
      venue: {
        name: "Central Park - Sheep Meadow",
        address: "Central Park",
        city: "New York",
        state: "NY",
        country: "USA",
        coordinates: { lat: 40.7712, lng: -73.9748 },
      },
    },
    images: {
      hero: "/images/events/health-1.jpg",
      thumbnail: "/images/events/health-1.jpg",
    },
    tickets: [
      {
        id: "tkt_030a",
        name: "Drop-In",
        price: 0,
        currency: "USD",
        description: "Free community event",
        features: ["60-min guided meditation", "Community gathering", "All levels welcome"],
        quantity: { total: 100, available: 45 },
      },
    ],
    tags: ["meditation", "mindfulness", "free", "morning", "wellness"],
    stats: { attendees: 55, views: 1234, saves: 89 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_031",
    title: "Soccer Tournament Finals",
    slug: "soccer-tournament-finals",
    description: "The culmination of the city's biggest amateur soccer tournament. Cheer on the finalists in this exciting championship match.",
    category: "sports",
    organizer: organizers[7],
    date: {
      start: daysFromNow(7, 14),
      end: daysFromNow(7, 17),
    },
    location: {
      type: "in-person",
      venue: {
        name: "City Sports Complex",
        address: "500 Stadium Dr",
        city: "Houston",
        state: "TX",
        country: "USA",
        coordinates: { lat: 29.7604, lng: -95.3698 },
      },
    },
    images: {
      hero: "/images/events/sports-stadium-1.jpg",
      thumbnail: "/images/events/sports-stadium-1.jpg",
    },
    tickets: [
      {
        id: "tkt_031a",
        name: "General Admission",
        price: 15,
        currency: "USD",
        description: "Open seating",
        features: ["Entry", "Access to all matches"],
        quantity: { total: 1000, available: 567 },
      },
    ],
    tags: ["soccer", "tournament", "sports", "championship", "amateur"],
    stats: { attendees: 433, views: 2345, saves: 123 },
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "evt_032",
    title: "Financial Freedom Workshop",
    slug: "financial-freedom-workshop",
    description: "Learn practical strategies for building wealth, managing investments, and achieving financial independence.",
    category: "education",
    organizer: organizers[6],
    date: {
      start: daysFromNow(19, 9),
      end: daysFromNow(19, 17),
    },
    location: {
      type: "online",
      onlineUrl: "https://financial-workshop.live",
    },
    images: {
      hero: "/images/events/business-1.jpg",
      thumbnail: "/images/events/business-1.jpg",
    },
    tickets: [
      {
        id: "tkt_032a",
        name: "Workshop Access",
        price: 79,
        currency: "USD",
        description: "Full day workshop",
        features: ["8-hour workshop", "Workbook", "Templates", "Community access"],
        quantity: { total: 300, available: 178 },
      },
    ],
    tags: ["finance", "investing", "wealth", "education", "money"],
    stats: { attendees: 122, views: 4567, saves: 345 },
    isFeatured: false,
    isTrending: false,
  },
];

// Categories with metadata
export const categories: { id: Category; name: string; icon: string; image: string; count: number }[] = [
  { id: "music", name: "Music", icon: "Music", image: "/images/categories/music.jpg", count: 156 },
  { id: "tech", name: "Technology", icon: "Cpu", image: "/images/categories/tech.jpg", count: 89 },
  { id: "food", name: "Food & Drink", icon: "UtensilsCrossed", image: "/images/categories/food.jpg", count: 234 },
  { id: "sports", name: "Sports", icon: "Trophy", image: "/images/categories/sports.jpg", count: 78 },
  { id: "arts", name: "Arts & Culture", icon: "Palette", image: "/images/categories/arts.jpg", count: 145 },
  { id: "networking", name: "Networking", icon: "Users", image: "/images/categories/networking.jpg", count: 167 },
  { id: "education", name: "Education", icon: "GraduationCap", image: "/images/categories/education.jpg", count: 312 },
  { id: "health", name: "Health & Wellness", icon: "Heart", image: "/images/categories/health.jpg", count: 98 },
];

// Helper functions
export const getFeaturedEvents = () => events.filter((e) => e.isFeatured);
export const getTrendingEvents = () => events.filter((e) => e.isTrending);
export const getEventsByCategory = (category: Category) => events.filter((e) => e.category === category);
export const getEventBySlug = (slug: string) => events.find((e) => e.slug === slug);
export const getEventById = (id: string) => events.find((e) => e.id === id);
export const getUpcomingEvents = () => {
  const now = new Date();
  return events.filter((e) => e.date.start > now).sort((a, b) => a.date.start.getTime() - b.date.start.getTime());
};
export const getFreeEvents = () => events.filter((e) => e.tickets.some((t) => t.price === 0));
export const searchEvents = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return events.filter(
    (e) =>
      e.title.toLowerCase().includes(lowerQuery) ||
      e.description.toLowerCase().includes(lowerQuery) ||
      e.tags.some((t) => t.toLowerCase().includes(lowerQuery))
  );
};
