import { KanbanBoard, Label } from "./types";

export const AVAILABLE_LABELS: Label[] = [
  { id: "bug", name: "Bug", color: "#ef4444" },
  { id: "feature", name: "Feature", color: "#3b82f6" },
  { id: "improvement", name: "Improvement", color: "#8b5cf6" },
  { id: "documentation", name: "Documentation", color: "#10b981" },
  { id: "design", name: "Design", color: "#f59e0b" },
];

export const MOCK_BOARD: KanbanBoard = {
  id: "board-1",
  title: "My Project Board",
  lists: [
    {
      id: "list-1",
      title: "To Do",
      status: "todo",
      tasks: [
        {
          id: "task-1",
          title: "Design landing page mockups",
          description: "Create high-fidelity mockups for the new landing page with focus on conversion optimization",
          status: "todo",
          priority: "high",
          labels: [AVAILABLE_LABELS[4]],
          assignee: "Alice Johnson",
          dueDate: "2025-11-30",
          createdAt: "2025-11-20T10:00:00Z",
          updatedAt: "2025-11-20T10:00:00Z",
        },
        {
          id: "task-2",
          title: "Set up CI/CD pipeline",
          description: "Configure GitHub Actions for automated testing and deployment",
          status: "todo",
          priority: "medium",
          labels: [AVAILABLE_LABELS[1]],
          assignee: "Bob Smith",
          createdAt: "2025-11-21T14:30:00Z",
          updatedAt: "2025-11-21T14:30:00Z",
        },
        {
          id: "task-3",
          title: "Update API documentation",
          description: "Document new endpoints and update existing ones",
          status: "todo",
          priority: "low",
          labels: [AVAILABLE_LABELS[3]],
          createdAt: "2025-11-22T09:15:00Z",
          updatedAt: "2025-11-22T09:15:00Z",
        },
      ],
    },
    {
      id: "list-2",
      title: "In Progress",
      status: "in-progress",
      tasks: [
        {
          id: "task-4",
          title: "Implement user authentication",
          description: "Add OAuth support with Google and GitHub providers",
          status: "in-progress",
          priority: "urgent",
          labels: [AVAILABLE_LABELS[1]],
          assignee: "Charlie Davis",
          dueDate: "2025-11-25",
          createdAt: "2025-11-18T11:20:00Z",
          updatedAt: "2025-11-23T08:45:00Z",
        },
        {
          id: "task-5",
          title: "Fix responsive navigation menu",
          description: "Mobile menu not closing properly on route change",
          status: "in-progress",
          priority: "high",
          labels: [AVAILABLE_LABELS[0]],
          assignee: "Alice Johnson",
          createdAt: "2025-11-22T16:00:00Z",
          updatedAt: "2025-11-23T10:30:00Z",
        },
      ],
    },
    {
      id: "list-3",
      title: "Review",
      status: "review",
      tasks: [
        {
          id: "task-6",
          title: "Add dark mode toggle",
          description: "Implement theme switching with next-themes",
          status: "review",
          priority: "medium",
          labels: [AVAILABLE_LABELS[2]],
          assignee: "Bob Smith",
          createdAt: "2025-11-19T13:45:00Z",
          updatedAt: "2025-11-23T09:00:00Z",
        },
      ],
    },
    {
      id: "list-4",
      title: "Done",
      status: "done",
      tasks: [
        {
          id: "task-7",
          title: "Setup project structure",
          description: "Initialize Next.js project with TypeScript and Tailwind",
          status: "done",
          priority: "high",
          labels: [AVAILABLE_LABELS[1]],
          assignee: "Charlie Davis",
          createdAt: "2025-11-15T09:00:00Z",
          updatedAt: "2025-11-16T17:30:00Z",
        },
        {
          id: "task-8",
          title: "Install shadcn/ui components",
          description: "Add necessary UI components from shadcn/ui library",
          status: "done",
          priority: "medium",
          labels: [AVAILABLE_LABELS[1]],
          assignee: "Alice Johnson",
          createdAt: "2025-11-16T10:15:00Z",
          updatedAt: "2025-11-17T11:20:00Z",
        },
      ],
    },
  ],
};
